### PR TITLE
Math Magicians: events

### PR DESCRIPTION
**Pull request by AmaliaGM**
## Project requirements

- To help you concentrate on how to work with React events, we have developed the math logic you need to make the Calculator component work. You can use the files [calculate.js](https://github.com/microverseinc/curriculum-react-redux/blob/main/math-magicians/code-samples/calculate.js) and [operate.js](https://github.com/microverseinc/curriculum-react-redux/blob/main/math-magicians/code-samples/operate.js).

- Copy the files calculate.js and operate.js into a logic/ directory in your project.
- Analyze the files calculate.js and operate.js, be sure you understand what they do (note: you need to add [big.js](https://www.npmjs.com/package/big-js) as dependency).
Import the files in your Calculator component.
- Implement the event handlers you need to use the math logic from calculate.js and operate.js in your React component.
- Practice what you have learned until now: use state and props, pass props to child components, use lifecycle methods, lift state up.
- Test your app in the browser. It should be able to perform math operations.

### CODE REVIEW

**Comment by ahmetbozaci** [comment]
# ❌ ❌ ❌ STATUS: INVALID  ❌ ❌ ❌ 


### Hello @AmaliaGM  ✋🏼 
#### You have submitted a project, that is using GitHub flow. You should use git-flow. Kindly change it. [Requirement](https://github.com/microverseinc/curriculum-react-redux/blob/main/math-magicians/project_events.md#:~:text=Make%20sure%20that%20you%20used%20correct%20Gitflow.)

#### Your Code Review Request will be marked as invalid in your Dashboard, so please submit a new one once you are ready 🙏


### Cheers and Happy coding! 💻 👏
coding

___

_Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification._

_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._

_Invalid Code Review Request **does not count** into the code reviews limit._

___

_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form.](https://airtable.com/shrQAqnBwek5a0O0s)_

[GitHub](https://github.com/ahmetbozaci) | [LinkedIn](https://linkedin.com/in/ahmetbozaci) | [Twitter](https://twitter.com/ahmtbozaci)

_Reviewed by [Ahmet Bozacı ](https://github.com/ahmetbozaci)_

**Comment by AmaliaGM** [comment]
Hi @ahmetbozaci  I hope you´re doing well. Please check out this way of working with git flow that I believe that´s what you mean (https://github.com/microverseinc/curriculum-transversal-skills/blob/main/git-github/articles/github_flow.md). I just didn´t call my feature branch "feature" but "functionality". Regards.

**Comment by ahmetbozaci** [comment]
@AmaliaGM 
- In the beginning, you have a master/main branch then you open a new branch(usually develop) from the master/main branch, then you should open a new branch from the develop branch. And your pull request develops to feature.

- Branches' names can be different but not to confuse the main and develop is the same but you can change the feature branch.
- In your case what is the master, develop and feature branches? Can you tell me?

**Your flow**
image

___
**Gitflow example**
image

**Comment by DeliceLydia** [comment]
## Hi @AmaliaGM, 

While you made a great effort in this project, unfortunately, I cannot proceed to review your code.

## Invalid Code Review Request

You have submitted a project, that does not follow git workflow, as the previous reviewer explained instead of opening your PR from `feature` branch to `master` you will open it from `feature` branch to the `develop` branch

Your Code Review Request will be marked as invalid in your Dashboard, so please submit a new one once you are ready 🙏

### Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

--------

_Invalid Code Review Request **does not count** into the code reviews limit._

**Comment by AmaliaGM** [comment]
> @AmaliaGM
> 
> * In the beginning, you have a master/main branch then you open a new branch(usually develop) from the master/main branch, then you should open a new branch from the develop branch. And your pull request develops to feature.
> * Branches' names can be different but not to confuse the main and develop is the same but you can change the feature branch.
> * In your case what is the master, develop and feature branches? Can you tell me?
> 
> **Your flow** image
> 
> **Gitflow example** image

Sure I can tell you. First there´s nothing I can do about it now (from the begining) since it was aproved like that. Now I´ve made a new branch called "functionality" that merges into "workspace" that merges into master.  Be kind. We are all here to learn.

**Comment by ahmetbozaci** [comment]
> > @AmaliaGM
> > 
> > * In the beginning, you have a master/main branch then you open a new branch(usually develop) from the master/main branch, then you should open a new branch from the develop branch. And your pull request develops to feature.
> > * Branches' names can be different but not to confuse the main and develop is the same but you can change the feature branch.
> > * In your case what is the master, develop and feature branches? Can you tell me?
> > 
> > **Your flow** image
> > **Gitflow example** image
> 
> Sure I can tell you. First there´s nothing I can do about it now (from the begining) since it was aproved like that. Now I´ve made a new branch called "functionality" that merges into "workspace" that merges into master. Be kind. We are all here to learn.

I was kind but sorry if you misunderstand to me. I just explained it to you how flow it should be. Can you send it for review again?

**Comment by AmaliaGM** [comment]
> 

 @ahmetbozaci  here is a link https://www.quora.com/What-is-the-difference-between-%E2%80%9Ccan-you%E2%80%9D-and-%E2%80%9Ccould-you%E2%80%9D that I think it would be good for your communication skills. Regards.

**Comment by ahmetbozaci** [comment]
@AmaliaGM 
I don't understand what did you see wrong in my texts. Again if you misunderstand something, ı am sorry. I just explain kindly how should flow and ı ask what is master, develop and feature branches in your case exactly.

**Comment by AmaliaGM** [comment]
> @AmaliaGM I don't understand what did you see wrong in my texts. Again if you misunderstand something, ı am sorry. I just explain kindly how should flow and ı ask what is master, develop and feature branches in your case exactly.

Have a nice day.

**Review by uwadonat — CHANGES_REQUESTED** [review]
## Hi @AmaliaGM,

While you made a great effort in this project, unfortunately, I cannot proceed to review your code.

## Invalid Code Review Request

You have submitted a project, that does not use `gitflow`.
Note: Kindly take your time and read the following document about how [gitflow](https://github.com/microverseinc/curriculum-transversal-skills/blob/main/git-github/articles/gitflow.md) works.

- [ ] in git flow `master/main` branch will not be default branch, because pull request will compare new branch to the development branch.
here is your branches:

branches

Your Code Review Request will be marked as invalid in your Dashboard, so please submit a new one once you are ready 🙏

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100%.
Please, remember to tag me @uwadonat in your question so I can receive the notification.

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._
```

**Comment by AmaliaGM** [comment]
I see. Thanks for explaining.

Obtener Outlook para Android<https://aka.ms/AAb9ysg>
________________________________

**Pull request merged**
